[package]
name = "example"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable.workspace = true
strum.workspace = true
splendor-core.workspace = true
splendor-ffi.workspace = true
