[package]
name = "splendor-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rand.workspace = true
serde.workspace = true
smallvec.workspace = true
splendor-core.workspace = true
strum.workspace = true
thiserror.workspace = true
