use crate::cards::{Card, Tier};
use splendor_core::{Color, ColorVec};

pub const TIRE1_CARDS: [Card; 40] = [
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 0, 3, 0, 0, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 0, 2, 1, 0, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 0, 2, 0, 2, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(1, 0, 1, 3, 0, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 2, 0, 1, 2, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 1, 1, 1, 1, 0)),
    Card::new(Tier::I, Color::Black, 0, ColorVec::new(0, 2, 1, 1, 1, 0)),
    Card::new(Tier::I, Color::Black, 1, ColorVec::new(0, 4, 0, 0, 0, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(3, 0, 0, 0, 0, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(2, 0, 0, 0, 1, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(2, 0, 2, 0, 0, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(0, 1, 3, 1, 0, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(0, 0, 2, 2, 1, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(1, 0, 1, 1, 1, 0)),
    Card::new(Tier::I, Color::Blue, 0, ColorVec::new(1, 0, 1, 2, 1, 0)),
    Card::new(Tier::I, Color::Blue, 1, ColorVec::new(0, 0, 0, 4, 0, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(0, 0, 0, 3, 0, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(0, 1, 0, 0, 2, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(0, 2, 0, 2, 0, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(0, 3, 1, 0, 1, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(2, 1, 0, 2, 0, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(1, 1, 0, 1, 1, 0)),
    Card::new(Tier::I, Color::Green, 0, ColorVec::new(2, 1, 0, 1, 1, 0)),
    Card::new(Tier::I, Color::Green, 1, ColorVec::new(4, 0, 0, 0, 0, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(0, 0, 0, 0, 3, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(0, 2, 1, 0, 0, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(0, 0, 0, 2, 2, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(3, 0, 0, 1, 1, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(2, 0, 1, 0, 2, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(1, 1, 1, 0, 1, 0)),
    Card::new(Tier::I, Color::Red, 0, ColorVec::new(1, 1, 1, 0, 2, 0)),
    Card::new(Tier::I, Color::Red, 1, ColorVec::new(0, 0, 0, 0, 4, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(0, 3, 0, 0, 0, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(1, 0, 0, 2, 0, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(2, 2, 0, 0, 0, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(1, 1, 0, 0, 3, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(1, 2, 2, 0, 0, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(1, 1, 1, 1, 0, 0)),
    Card::new(Tier::I, Color::White, 0, ColorVec::new(1, 1, 2, 1, 0, 0)),
    Card::new(Tier::I, Color::White, 1, ColorVec::new(0, 0, 4, 0, 0, 0)),
];

pub const TIRE2_CARDS: [Card; 30] = [
    Card::new(Tier::II, Color::Black, 1, ColorVec::new(0, 2, 2, 0, 3, 0)),
    Card::new(Tier::II, Color::Black, 1, ColorVec::new(2, 0, 3, 0, 3, 0)),
    Card::new(Tier::II, Color::Black, 2, ColorVec::new(0, 0, 0, 0, 5, 0)),
    Card::new(Tier::II, Color::Black, 2, ColorVec::new(0, 5, 0, 3, 0, 0)),
    Card::new(Tier::II, Color::Black, 2, ColorVec::new(0, 1, 4, 2, 0, 0)),
    Card::new(Tier::II, Color::Black, 3, ColorVec::new(6, 0, 0, 0, 0, 0)),
    Card::new(Tier::II, Color::Blue, 1, ColorVec::new(0, 2, 2, 3, 0, 0)),
    Card::new(Tier::II, Color::Blue, 1, ColorVec::new(3, 2, 3, 0, 0, 0)),
    Card::new(Tier::II, Color::Blue, 2, ColorVec::new(0, 5, 0, 0, 0, 0)),
    Card::new(Tier::II, Color::Blue, 2, ColorVec::new(0, 3, 0, 0, 5, 0)),
    Card::new(Tier::II, Color::Blue, 2, ColorVec::new(4, 0, 0, 1, 2, 0)),
    Card::new(Tier::II, Color::Blue, 3, ColorVec::new(0, 6, 0, 0, 0, 0)),
    Card::new(Tier::II, Color::Green, 1, ColorVec::new(2, 3, 0, 0, 2, 0)),
    Card::new(Tier::II, Color::Green, 1, ColorVec::new(0, 0, 2, 3, 3, 0)),
    Card::new(Tier::II, Color::Green, 2, ColorVec::new(0, 0, 5, 0, 0, 0)),
    Card::new(Tier::II, Color::Green, 2, ColorVec::new(0, 5, 3, 0, 0, 0)),
    Card::new(Tier::II, Color::Green, 2, ColorVec::new(1, 2, 0, 0, 4, 0)),
    Card::new(Tier::II, Color::Green, 3, ColorVec::new(0, 0, 6, 0, 0, 0)),
    Card::new(Tier::II, Color::Red, 1, ColorVec::new(3, 0, 0, 2, 2, 0)),
    Card::new(Tier::II, Color::Red, 1, ColorVec::new(3, 3, 0, 2, 0, 0)),
    Card::new(Tier::II, Color::Red, 2, ColorVec::new(5, 0, 0, 0, 0, 0)),
    Card::new(Tier::II, Color::Red, 2, ColorVec::new(5, 0, 0, 0, 3, 0)),
    Card::new(Tier::II, Color::Red, 2, ColorVec::new(0, 4, 2, 0, 1, 0)),
    Card::new(Tier::II, Color::Red, 3, ColorVec::new(0, 0, 0, 6, 0, 0)),
    Card::new(Tier::II, Color::White, 1, ColorVec::new(2, 0, 3, 2, 0, 0)),
    Card::new(Tier::II, Color::White, 1, ColorVec::new(0, 3, 0, 3, 2, 0)),
    Card::new(Tier::II, Color::White, 2, ColorVec::new(0, 0, 0, 5, 0, 0)),
    Card::new(Tier::II, Color::White, 2, ColorVec::new(3, 0, 0, 5, 0, 0)),
    Card::new(Tier::II, Color::White, 2, ColorVec::new(2, 0, 1, 4, 0, 0)),
    Card::new(Tier::II, Color::White, 3, ColorVec::new(0, 0, 0, 0, 6, 0)),
];

pub const TIRE3_CARDS: [Card; 20] = [
    Card::new(Tier::III, Color::Black, 3, ColorVec::new(0, 3, 5, 3, 3, 0)),
    Card::new(Tier::III, Color::Black, 4, ColorVec::new(3, 0, 3, 6, 0, 0)),
    Card::new(Tier::III, Color::Black, 4, ColorVec::new(0, 0, 0, 7, 0, 0)),
    Card::new(Tier::III, Color::Black, 5, ColorVec::new(3, 0, 0, 7, 0, 0)),
    Card::new(Tier::III, Color::Blue, 3, ColorVec::new(5, 0, 3, 3, 3, 0)),
    Card::new(Tier::III, Color::Blue, 4, ColorVec::new(3, 3, 0, 0, 6, 0)),
    Card::new(Tier::III, Color::Blue, 4, ColorVec::new(0, 0, 0, 0, 7, 0)),
    Card::new(Tier::III, Color::Blue, 5, ColorVec::new(0, 3, 0, 0, 7, 0)),
    Card::new(Tier::III, Color::Green, 3, ColorVec::new(3, 3, 0, 3, 5, 0)),
    Card::new(Tier::III, Color::Green, 4, ColorVec::new(0, 6, 3, 0, 3, 0)),
    Card::new(Tier::III, Color::Green, 4, ColorVec::new(0, 7, 0, 0, 0, 0)),
    Card::new(Tier::III, Color::Green, 5, ColorVec::new(0, 7, 3, 0, 0, 0)),
    Card::new(Tier::III, Color::Red, 3, ColorVec::new(3, 5, 3, 0, 3, 0)),
    Card::new(Tier::III, Color::Red, 4, ColorVec::new(0, 3, 6, 3, 0, 0)),
    Card::new(Tier::III, Color::Red, 4, ColorVec::new(0, 0, 7, 0, 0, 0)),
    Card::new(Tier::III, Color::Red, 5, ColorVec::new(0, 0, 7, 3, 0, 0)),
    Card::new(Tier::III, Color::White, 3, ColorVec::new(3, 3, 3, 5, 0, 0)),
    Card::new(Tier::III, Color::White, 4, ColorVec::new(6, 0, 0, 3, 3, 0)),
    Card::new(Tier::III, Color::White, 4, ColorVec::new(7, 0, 0, 0, 0, 0)),
    Card::new(Tier::III, Color::White, 5, ColorVec::new(7, 0, 0, 0, 3, 0)),
];
